export const USER_ADD_REQUEST = 'USER_ADD_REQUEST';
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const USER_ADD_ERROR = 'USER_ADD_ERROR';

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_ERROR = 'USER_EDIT_ERROR';

export const USER_GET_BY_ID_REQUEST = 'USER_GET_BY_ID_REQUEST';
export const USER_GET_BY_ID_SUCCESS = 'USER_GET_BY_ID_SUCCESS';
export const USER_GET_BY_ID_ERROR = 'USER_GET_BY_ID_ERROR';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';